### ISSUE TITLE
"Oops! We've encountered an error. Please try again."

### ISSUE THREAD

**Issue by jzigmond** [tonesto7/nest-manager#555]
Have checked configuration multiple times, still receiving this error after Nest login when attempting to grant "works with Nest' permissions. 
Login goes fine, when I click accept- I receive the error above. 

Known issue, or am I doing something wrong?

**Comment by jzigmond** [comment]
Resolved- was a permissions issue. Thanks for all the work on this!

**Comment by waltmoorhouse** [comment]
@jzigmond can you elaborate on the solution? I'm encountering this error as well.

**Comment by jzigmond** [comment]
Following this set of instructions on the google auth exactly.
Specifically- permissions for access to the resources (part2):
https://rawgit.com/tonesto7/nest-manager/master/Documents/instructions/Nest%20Developer%20-%20Nest%20Product.pdf

**Comment by Atily** [comment]
I have followed all instructions and I am unable to integrate with nest.

**Comment by cpmorris1001** [comment]
@Atily I had similar symptoms and eventually was able to clear the problem.
1)Please see screen capture of the error.  Just FYI on by using the reload “circle arrow” at the bottom of the page I was able to successfully log in on the second attempt.  [NOTE: this did not solve the problem]
2) Ultimately I had to log onto the Nest Developers site using a **non-mobile** device.  When I logged into the Nest Developers site on a **non-mobile** device the error did not occur and after doing this I think a corruption was cleared and trying again during the NST MNGR set up worked
![05f588fa-8e11-4e57-9905-3141a74c60aa](https://user-images.githubusercontent.com/37513441/42410927-89b1d7a4-81af-11e8-80f0-d8ef1c09c5d5.png)

**Comment by Atily** [comment]
@cpmorris1001 Thanks for the info. I followed all instructions to create a developer account and obtain the ID and the client secret. I was able to log on to Nest following that. I am not a IT guy I am a lay person. I had no idea that one has to go through the steps to use an app. My NST manager stopped working in February. I left it at that, no one informed me that there is an update. Once I updated I ran in to the problem. I uninstalled the app and reinstalled. Then I created the developer account to obtain the ID and secret.

**Comment by cpmorris1001** [comment]
@Atily did this solve your problem ?

**Comment by Atily** [comment]
@cpmorris1001 Yes thank you. Nest Manager is fully functional now.
